### ISSUE TITLE
App crashes at startup on api levels 21-25 (Android 5.0 - Android 7.1)

### ISSUE THREAD

**Issue by Sergey-Makarov** [fingerprintjs/fingerprint-device-intelligence-android-demo#5]
This crash is NOT related to the Fingerprint Pro SDK, but only to the implementation of the demo app itself.

The root cause of the issue is that the used version of `jackson-databind` dependency is [not compatible](https://github.com/square/retrofit/issues/4131) with Android SDK 21-25.

We'll get it fixed in the next version of the demo app.

Stacktrace:
```
 java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/BootstrapMethodError;
at com.fasterxml.jackson.databind.util.ExceptionUtil.isFatal(ExceptionUtil.java:51)
at com.fasterxml.jackson.databind.util.ExceptionUtil.rethrowIfFatal(ExceptionUtil.java:31)
at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.<clinit>(JacksonAnnotationIntrospector.java:70)
at com.fasterxml.jackson.databind.ObjectMapper.<clinit>(ObjectMapper.java:402)
at com.fingerprintjs.android.fpjs_pro_demo.di.modules.AppModule.provideObjectMapper(AppModule.kt:36)
at com.fingerprintjs.android.fpjs_pro_demo.di.modules.AppModule_ProvideObjectMapperFactory.provideObjectMapper(AppModule_ProvideObjectMapperFactory.java:38)
at com.fingerprintjs.android.fpjs_pro_demo.di.modules.AppModule_ProvideObjectMapperFactory.get(AppModule_ProvideObjectMapperFactory.java:30)
at com.fingerprintjs.android.fpjs_pro_demo.di.modules.AppModule_ProvideObjectMapperFactory.get(AppModule_ProvideObjectMapperFactory.java:11)
at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
at com.fingerprintjs.android.fpjs_pro_demo.di.DaggerAppComponent$AppComponentImpl.jacksonSerializer(DaggerAppComponent.java:89)
at com.fingerprintjs.android.fpjs_pro_demo.di.DaggerAppComponent$AppComponentImpl.appStorage(DaggerAppComponent.java:93)
at com.fingerprintjs.android.fpjs_pro_demo.di.DaggerAppComponent$AppComponentImpl.showSignUpPromptUseCase(DaggerAppComponent.java:97)
at com.fingerprintjs.android.fpjs_pro_demo.di.DaggerAppComponent$AppComponentImpl.getHomeViewModel(DaggerAppComponent.java:115)
at com.fingerprintjs.android.fpjs_pro_demo.ui.screens.home.HomeScreenKt$HomeScreen$$inlined$injectedViewModel$1.create(Extensions.kt:37)
at androidx.lifecycle.ViewModelProvider$Factory.create(ViewModelProvider.kt:83)
at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:184)
at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:150)
at androidx.lifecycle.viewmodel.compose.ViewModelKt.get(ViewModel.kt:215)
at androidx.lifecycle.viewmodel.compose.ViewModelKt.viewModel(ViewModel.kt:156)
at com.fingerprintjs.android.fpjs_pro_demo.ui.screens.home.HomeScreenKt.HomeScreen(HomeScreen.kt:282)
.....
```

**Comment by Sergey-Makarov** [comment]
Fixed in #9
